apps/server/src/controllers/project.js
apps/server/src/controllers/repository.js
apps/server/src/routes/project.spec.js

Besoin d'entourer requêtes `fetch` avec un try catch car :
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
`The Promise returned from fetch() won't reject on HTTP error status even if the response is an HTTP 404 or 500`

fix: :goal_net: catch fetch errors and send it to front

---

.github/workflows/release.yml

Improve ci :
- bump `docker/build-push-action` from `v3` to `v4`
- add `latest` tag on images build after release

ci: :construction_worker: bump action version & add latest tag to images

---

.eslintignore
.gitignore
apps/client/cypress/e2e/specs/admin/logs.e2e.js
apps/client/package.json
apps/client/src/api/api.js
apps/client/src/components/CIForm.vue
apps/client/src/components/SideMenu.vue
apps/client/src/icons.js
apps/client/src/main.ts
apps/client/src/router/index.js
apps/client/src/stores/admin/log.js
apps/client/src/stores/admin/log.spec.js
apps/client/src/views/ServicesHealth.vue
apps/client/src/views/admin/ListLogs.vue
apps/client/uno.config.ts
apps/server/src/controllers/admin/logs.ts
apps/server/src/init/db/setup-projects.ts
apps/server/src/models/queries/log-queries.ts
apps/server/src/routes/admin/index.ts
apps/server/src/routes/admin/log.spec.ts
apps/server/src/routes/admin/log.ts
packages/shared/src/utils/const.js
packages/shared/src/utils/date.js
packages/test-utils/src/imports/data.js
packages/test-utils/src/random-utils.js
pnpm-lock.yaml

Closes #443 
- ~Logs regroupés par projet~
Filtres à faire dans une autre PR  :
- réflexion filtre par `projectId` car pas cette clé dans la table `Logs`. Est-ce qu'un log sera toujours lié à un projet ? Ou il peut y avoir des logs hors projet ?

feat: :sparkles: add admin log page

---

apps/client/Dockerfile
apps/client/cypress/components/specs/cluster-form.ct.js
apps/client/cypress/components/specs/multi-selector.ct.js
apps/client/cypress/e2e/specs/admin/clusters.e2e.js
apps/client/package.json
apps/client/src/api/api.js
apps/client/src/components/ClusterForm.vue
apps/client/src/components/EnvironmentForm.vue
apps/client/src/components/MultiSelector.vue
apps/client/src/components/SideMenu.vue
apps/client/src/main.css
apps/client/src/router/index.js
apps/client/src/stores/admin/cluster.js
apps/client/src/stores/admin/cluster.spec.js
apps/client/src/views/admin/ListClusters.vue
apps/client/src/views/admin/ListLogs.vue
apps/server/Dockerfile
apps/server/src/controllers/admin/cluster.ts
apps/server/src/routes/admin/cluster.ts
packages/shared/package.json
packages/shared/src/schemas/cluster.ts
packages/shared/src/schemas/index.ts
packages/test-utils/src/random-utils.js
pnpm-lock.yaml

- remanier `ClusterForm.vue`  : 
- `user` => si pas de current context, prendre le premier `contexts.context.user` => trouver `users.name` correspondant
- `cluster` => si pas de current context, prendre le premier `contexts.context.cluster` =>  trouver `clusters.cluster.name` correspondant / `tlsServerName` construit à partir de `clusters.cluster.server` sans https:// ni :4000 (sni)

feat: :sparkles: introduce cluster managment frontend

---

apps/client/cypress/e2e/specs/admin/projects.e2e.js
apps/client/src/components/PermissionForm.vue
apps/client/src/views/admin/ListClusters.vue
apps/client/src/views/admin/ListOrganizations.vue
apps/client/src/views/admin/ListProjects.vue
apps/client/src/views/projects/DsoProjects.vue
apps/client/src/views/projects/DsoRepos.vue
apps/client/src/views/projects/ManageEnvironments.vue
packages/shared/src/utils/functions.ts

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted#browser_compatibility
`toSorted` supporté par `node` à partir de la version `20`.
Mais on ne l'utilise que dans le front, donc ce sera les navigateurs qui le calculeront.

refactor: :recycle: use toSorted instead of sort

---

apps/server/src/prisma/migrations/20231026150220_dso/migration.sql

Pour la migrations v6 les projets pourraient s'unlock malencontreusement
Empeche que ce soit le cas sur les anciens projets à migrer

fix: :card_file_box: set all project status to failed for v6 release

---

.github/workflows/tests-component.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-unit.yml
.vscode/settings.json
turbo.json

---------
Il est uniquement possible de lancer les tests unitaire par le pipeline de CI complet.
Il est possible de lancer les tests unitaire manuellement avec l'analyse Sonar de la branche qui a déclenché le workflow.
Non

ci: :construction_worker: enable manual trigger on unit tests in ci

---

apps/client/cypress/components/specs/environment-form.ct.ts
apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
apps/client/cypress/e2e/specs/admin/projects.e2e.ts
apps/client/cypress/e2e/specs/environments.e2e.ts
apps/client/src/components/EnvironmentForm.vue
apps/client/src/components/StageForm.vue
apps/client/src/views/CreateProject.vue
packages/shared/src/schemas/environment.ts
packages/shared/src/schemas/project.ts
packages/shared/src/schemas/stage.ts
packages/test-utils/src/imports/data.ts

Ne pas autoriser les traits d'union dans les noms d'environnement, de projet et de stage (exploit a besoin de faire des requêtes avec des regex séparant les ressources par trait d'union).

feat: :sparkles: disallow hyphen on project, environment and stage

---

apps/server/src/resources/project/business.ts
apps/server/src/resources/repository/business.ts
apps/server/src/resources/user/business.ts
apps/server/src/utils/business.ts

---------
On ne reçoit pas la payload dans un log d'échec de `validate`.
On ne sait pas non plus quel plugin envoie quelle erreur.
On reçoit désormais la réponse entière des plugins, exactement comme lors d'un `execute` :
```js
{
"id": "5b1b0155-2e53-4062-9a76-1c125cb3e77d",
"data": {
"args": {
"owner": {
"id": "db14f17d-a54d-4376-8b8d-603cbaf774b7",
"email": "claire.nollet@interieur.gouv.fr",
"lastName": "Nollet",
"firstName": "Claire"
}
},
"failed": true,
"gitlab": {
"error": "{}",
"status": {
"result": "KO",
"message": "Erreur !!!"
}
},
"sonarqube": {
"status": {
"result": "OK",
"message": ""
}
}
},
"userId": "db14f17d-a54d-4376-8b8d-603cbaf774b7"
}
```

feat: :loud_sound: add payload and full hook response in validation failed log

---

apps/client/cypress/components/specs/stage-form.ct.ts
apps/client/src/App.vue
apps/client/src/components/EnvironmentForm.vue
apps/client/src/components/QuotaForm.vue
apps/client/src/components/RepoForm.vue
apps/client/src/components/StageForm.vue
apps/client/src/components/TeamCt.vue
apps/client/src/stores/snackbar.ts
apps/client/src/views/CreateProject.vue
apps/client/src/views/admin/ListProjects.vue
apps/client/src/views/admin/ListQuotas.vue
apps/client/src/views/admin/ListStages.vue
apps/client/src/views/projects/DsoDashboard.vue
apps/client/src/views/projects/DsoRepos.vue
apps/client/src/views/projects/DsoTeam.vue
apps/client/src/views/projects/ManageEnvironments.vue

---------
La gestion d'erreur dans un handler global (App.vue) ne permet plus de passer le booléen conditionnant la visibilité du LoadingCt.vue => en cas d'erreur, on reste sur le loading.
Le booléen conditionnant la visibilité du LoadingCt.vue est partagé entre les vues et composants via le store => en cas d'erreur, on ne reste pas sur le loading.

fix: :bug: share loadingct display knowledge

---

apps/server/src/__mocks__/app.ts
apps/server/src/app.ts
apps/server/src/resources/cluster/admin/business.ts
apps/server/src/resources/environment/business.ts
apps/server/src/resources/environment/controllers.spec.ts
apps/server/src/resources/environment/controllers.ts
apps/server/src/resources/log/admin/queries.ts
apps/server/src/resources/organization/admin/business.ts
apps/server/src/resources/organization/controllers.ts
apps/server/src/resources/permission/business.ts
apps/server/src/resources/permission/queries.ts
apps/server/src/resources/project/business.ts
apps/server/src/resources/project/controllers.ts
apps/server/src/resources/project/queries.ts
apps/server/src/resources/quota/admin/business.ts
apps/server/src/resources/quota/admin/controllers.ts
apps/server/src/resources/stage/admin/business.ts
apps/server/src/resources/user/business.ts
apps/server/src/resources/user/controllers.spec.ts
apps/server/src/utils/controller.ts
packages/hooks/src/hooks/project.ts
packages/shared/src/resources/environment/openApiSchema.ts
packages/shared/src/resources/permission/openApiSchema.ts
packages/shared/src/resources/project/openApiSchema.ts
packages/shared/src/resources/quota/openApiSchema.ts
packages/shared/src/resources/stage/openApiSchema.ts
packages/shared/src/resources/user/openApiSchema.ts

refactor: :rotating_light: fix ts errors in server

---

.github/workflows/build.yml
release-please-config.json

---------
- Le tag est créé avec le nom du composant qui est release, dans notre cas le tag est `console-vX.Y.Z` au lieu de `vX.Y.Z`
- Les images ne se builds pas à cause de conflits sur les noms des artefacts uploadés (conflits dans la matrice Github entre le build `amd64` et `arm64`)
- Le tag ne devrait plus inclure le composant release (nous en avons qu'un seul donc préférons ne pas le spécifier)
- Les images ne devrait plus avoir de conflits sur l'upload de leurs artefacts.
Non

fix: :green_heart: fix ci-cd build and release

---

apps/server/src/plugins.ts

---------
Les plugins externes ne sont pas correctement importés car l'import est fait sur le dossier du plugin, ce qui n'est pas possible via les imports ESM.
Le plugin manager parse le `package.json` du plugin pour y trouver le point d'entrée `module` ou `main` et importer ce fichier plutôt que le dossier complet.
Non

fix: :bug: correctly handle external plugins init

---

.github/workflows/build.yml

---------
Lorsque l'on déclenche un build des images manuellement dans la CI, le tag n'est pas correctement déterminé en utilisant la branche qui a déclenché le workflow.
Lorsque l'on déclenche un build des images manuellement dans la CI, le tag est correctement déterminé.
Non

ci: :green_heart: fallback to trigger branch name on manual build

---

apps/client/cypress/e2e/specs/admin/logs.e2e.ts
apps/client/cypress/e2e/specs/admin/projects.e2e.ts
apps/client/cypress/e2e/specs/dashboard.e2e.ts
apps/client/src/api/projects.spec.ts
apps/client/src/api/projects.ts
apps/client/src/stores/project.ts
apps/client/src/views/admin/ListProjects.vue
apps/client/src/views/projects/DsoDashboard.vue
apps/server/src/resources/cluster/business.ts
apps/server/src/resources/project/business.ts
apps/server/src/resources/project/controllers.spec.ts
apps/server/src/resources/project/router.ts
packages/shared/src/contracts/project.ts
packages/shared/src/schemas/project.ts

Ajout d'un bouton "Reprovisionner le projet" sur les pages `projects/dashboard` et `admin/projects`
---------

feat: :sparkles: add replay hooks button for project

---

helm/templates/deployment-postgres.yaml
helm/values.yaml

---------
Il est actuellement impossible d'injecter des annotations sur le statefulset postgres déployé par le chart CPiN.
Il est désormais possible d'injecter des annotations sur le statefulset postgres déployé par le chart CPiN (via les `values.yaml`).
Non

ci: :construction_worker: add postgres annotations in helm chart

---

.github/workflows/tests-component.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-unit.yml

---------
Le cache de la CI pendant les tests unitaires n'est pas correctement restauré ce qui fait tomber la CI en échec. Actuellement uniquement les fichiers turbo / de coverage sont restaurés.
Désormais le cache des tests unitaires embarque aussi les dossiers `src/`, `dist/` ou encore `types/`.
Non

ci: :construction_worker: restore all files on unit tests cache hit

---

apps/client/vite.config.ts

---------
Actuellement l'ensemble des variables d'environnement du client sont chargées lors de la phase de build de production de l'application.
Uniquement la variable `APP_VERSION` est chargée lors de la phase de build de production, c'est la seule à devoir être chargée pour injecter le numéro de version de l'application durant cette phase, les autres variables étant peuplées lors de la phase de run de l'application.
Non.

fix: :bug: get only client app version from env on production build

---

helm/templates/cm-postgres.yaml
helm/templates/cm-scripts.yaml
helm/templates/cm-server.yaml
helm/templates/deployment-postgres.yaml
helm/templates/services-postgres.yaml
helm/templates/services.yaml
helm/values.yaml

---------
Il est actuellement impossible de désactiver le déploiement de postgres dans le chart Helm.
Il existe désormais une clé `postgres.enabled` (par défaut `true`) pour désactiver le déploiement du postgres.
Non.
- Permet le futur remplacement du postgres déployé par un cluster CNPG.
- Fix le problème de plugins déjà présents sur l'init-container.

refactor: :recycle: handle disabling helm postgres deployment

---

plugins/vault/package.json
plugins/vault/src/monitor.ts

Le check du statut de Vault ne renvoi pas nécessairement `statusCode: 200` dans le cas d'un cluster Vault.
Le check du statut de Vault renvoi `statusCode: 200` même s'il la requête tombe sur un noeud en standby.
cf. https://developer.hashicorp.com/vault/api-docs/system/health#parameters
Non.

fix: :bug: handle vault ha for status monitor

---

apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
apps/client/cypress/e2e/specs/admin/projects.e2e.ts
apps/client/cypress/e2e/specs/admin/quotas.e2e.ts
apps/client/src/components/EnvironmentForm.vue
packages/test-utils/src/imports/data.ts

Pour un admin membre d'un projet qui souhaiterait modifier ou ajouter un environnement, on affiche la liste de tous les quotas, y compris les quotas privés.
On n'affiche plus les quotas privés sur le formulaire de modification ou de création d'un environnement, peu importe le rôle de la personne.
L'admin a toujours accès au quota privé dans la liste admin des projets.

feat: :necktie: hide private quotas for all on environment form

---

apps/server/src/resources/cluster/admin/business.ts
apps/server/src/resources/cluster/business.ts
apps/server/src/resources/quota/business.ts
packages/eslintconfig/index.js

---------
Message d'erreur "Vous n'êtes pas connecté" sur les pages d'admin lorsque la table User ne contient pas encore l'utilisateur connecté avec keycloak (premières connexions)
Plus de message d'erreur grâce au passage par un `getOrCreateUser`

fix: 🐛 insert user when first accessing admin pages

---

plugins/argocd/src/functions.ts
plugins/kubernetes/src/api.ts

---------
Un kubeconfig en mode user token est considéré comme un cluster inaccessible.
Le kubeconfig avec token est bien utilisé pour communiquer avec le cluster.

fix: :bug: don't ignore user token when testing cluster deployment mode

---

apps/client/src/components/ClusterForm.vue

Ajoute le nom du cluster dans la page de modification des clusters:
Exemple:
Avant:
`Mettre à jour le cluster`
Après:
`Mettre à jour le cluster pas-top-cluster`

fix: add label to page update cluster

---

.github/labeler/build.yml
.github/workflows/ci.yml
.github/workflows/label.yml
.github/workflows/preview.yml
ci/preview/applicationset.yaml

Il n'est pas possible d'utiliser les preview apps.
Ajoute la gestion des preview apps. Si on ajoute le label `preview` sur la PR :
- Déploie une app Argo-cd avec les images construites dans la PR.
- Ajoute un commentaire sur la PR avec l'url de la console.
Les utilisateurs créés dans Keycloak sont :
- Un utilisateur admin *- `admin`*.
- Un utilisateur standard *- `test`*.
L'application est détruite si on retire le tag / close la PR / merge la PR.
Non.
Cette fonctionnalité utilise le [pull request generator de Argo-cd](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/#github).
J'ai dû faire des release du chart de la console pour permettre l'import d'un realm de dev.

ci: :construction_worker: handle app preview

---

.github/workflows/scan.yml
.github/workflows/tests-component.yml
.github/workflows/tests-e2e.yml

Il y a un conflit de nom d'artefact entre les tests e2e et de composant.
- Il n'y a plus de conflit d'artefacts.
- Ajout d'un commentaire vers le rapport de scan de sécurité.
Non.

ci: :construction_worker: fix cypress artifacts upload

---

.github/workflows/scan.yml

Le pull de l'image Trivy est parfois bloqué par le rate limit :
```sh
GET https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2: TOOMANYREQUESTS: retry-after: 103.354µs, allowed: 44000/minute
```
L'authentification par token Github doit remédier aux problèmes de rate limit (cf. [la doc](https://aquasecurity.github.io/trivy/v0.55/docs/references/troubleshooting/#github-rate-limiting).
Non.

ci: :construction_worker: fix trivy pull rate limits

---

apps/server/src/resources/cluster/queries.ts
apps/server/src/utils/hook-wrapper.ts
packages/hooks/src/hooks/index.ts
plugins/argocd/src/cluster.ts
plugins/argocd/src/functions.ts
plugins/argocd/src/index.ts
plugins/argocd/src/zone.ts
plugins/gitlab/src/index.ts
plugins/vault/src/class.ts
plugins/vault/src/functions.ts
plugins/vault/src/index.ts

feat: :sparkles: store cluster secret in Vault

---

apps/server/src/resources/user/business.spec.ts
apps/server/src/resources/user/business.ts

Résout le ticket: #1596 
Lorsqu'un utilisateur Administrateur se connecte pour la première fois, la section "Administration" n'apparaît pas.
Lorsqu'un utilisateur Administrateur se connecte pour la première fois, la section "Administration" apparaît.
Non.

Fix admin roles not being retrieved when a new user logs in for the first time

---

plugins/gitlab/src/class.ts
plugins/gitlab/src/functions.ts
plugins/gitlab/src/group.ts
plugins/gitlab/src/repositories.ts

Issues numéro:
---------
Avec Gitlab 18.x :
- le groupe n'est plus immédiatement supprimé lors de la suppression du projet, mais au bout de 7 jours
- les suppressions de projects (dépôts) échouent avec l'erreur "Project must be marked for deletion first."
Implémentation du double d'appel d'API pour une suppression immédiate, tel que préconisé par la documentation :
https://docs.gitlab.com/api/projects/#delete-a-project

fix: :bug: fix gitlab deletion API request

---

apps/client/src/components/ProjectResources.vue

Issues numéro:
[#1635](https://github.com/cloud-pi-native/console/issues/1635)
---------
L'utilisateur ne pouvait pas récupérer facilement l'ID d'un projet
L'utilisateur peut désormais recuperer l'id  depuis la modal depuis le bouton "Recuperer l'ID du dépôt

feat: ✨ Add the repo UID display on console

---

apps/client/cypress/e2e/specs/repos.e2e.ts
apps/client/package.json
apps/client/src/components/ProjectResources.vue
pnpm-lock.yaml

Issues numéro: #1669 
La version actuellement utilisée (v14.0) ne supporte pas le Webdriver BiDi qui est désormais le seul moyen pour Cypress d'automatiser Firefox. L'ancien protocole (CDP) était déprécié et a été abandonné dans la dernière (`latest`) version de Firefox (v141).
La version 14.5.2 (la dernière v14.x en date) de Cypress est utilisée. Les tests sont OK.
Non.

Bump Cypress v14.5.2
