cloud-pi-native/console

- apps/client/cypress/e2e/specs/repos.e2e.js
- apps/client/cypress/e2e/support/commands.js
- apps/client/src/components/RepoForm.vue
- apps/server/src/controllers/project.js
- apps/server/src/models/project-queries.js
- apps/server/src/routes/project.spec.js
- apps/server/src/utils/__tests__/random-util.js
- packages/shared/dev-setup/projects.js
- packages/shared/src/schemas/repo.js
- packages/shared/src/utils/schemas.spec.js
> feat: :sparkles: add infra repo checkbox

- apps/client/cypress/e2e/specs/create-project.e2e.js
- apps/client/cypress/e2e/support/commands.js
- apps/client/src/views/CreateProject.vue
- apps/server/src/controllers/project.js
- apps/server/src/utils/__tests__/project-util.js
- apps/server/src/utils/__tests__/random-util.js
- packages/shared/dev-setup/projects.js
- packages/shared/src/schemas/project.js
> feat: :sparkles: Add envList to project

- .gitignore
- apps/client/cypress.config.js
- apps/client/cypress/e2e/specs/services.e2e.js
- apps/client/nginx/entrypoint.sh
- apps/client/src/utils/env.js
- apps/client/src/views/projects/DsoServices.vue
- docker/docker-compose.ci.yml
- docker/docker-compose.dev.yml
- docker/docker-compose.e2e.yml
- docker/docker-compose.prod.yml
- env/.env-example
- env/.env.ci-example
> feat: :sparkles: Adding correct services url

- apps/client/src/utils/keycloak/keycloak.js
bug FF qui n'authentifie pas dans ce cas
> fix: :alembic: changement du keycloak flow

- apps/client/cypress/e2e/support/commands.js
- apps/client/src/views/CreateProject.vue
- packages/shared/dev-setup/projects.js
- packages/shared/src/schemas/project.js
Suppr doublon `envList` et `allEnv`
> refactor: :recycle: remove double const for allEnv

- apps/client/package.json
- apps/client/src/components/SideMenu.vue
- apps/client/src/main.css
- apps/client/src/views/CreateProject.vue
- pnpm-lock.yaml
> fix: :lipstick: update UI for new DSFR version

- apps/client/src/App.vue
- apps/client/src/views/projects/DsoSelectedProject.vue
- apps/client/src/views/projects/DsoTeam.vue
> feat: :sparkles: display current user name in closeable alert

- apps/client/src/App.vue
> feat: :lipstick: fix snackbar on bottom left

- apps/server/src/utils/crypto.js
Improve #163 
Cf. https://nodejs.org/api/crypto.html#cryptotimingsafeequala-b
> fix: :lock: improve security using node utility function to compare hashes

- apps/server/src/utils/crypto.js
- apps/server/src/utils/crypto.spec.js
> feat: :sparkles: add backend function to generate random passwords

- apps/client/cypress/components/specs/permission-form.ct.js
- apps/server/src/generate-files/generate-ci-files.spec.js
- apps/server/src/routes/organization.spec.js
- apps/server/src/routes/project-environment.spec.js
- apps/server/src/routes/project-permission.spec.js
- apps/server/src/routes/project-repository.spec.js
- apps/server/src/routes/project-user.spec.js
- apps/server/src/routes/project.spec.js
- apps/server/src/utils/random.spec.js
- packages/test-utils/src/random-project.js
- packages/test-utils/src/random-utils.js
```
⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
server:test: 
server:test: Vitest caught 1 unhandled error during the test run.
server:test: This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
server:test: 
server:test: ⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
server:test: Error: must have required property 'url',must have required property 'path',must match exactly one schema in oneOf
server:test:  ❯ doInject ../../node_modules/.pnpm/light-my-request@5.8.0/node_modules/light-my-request/index.js:38:13
server:test:  ❯ Chain.end ../../node_modules/.pnpm/light-my-request@5.8.0/node_modules/light-my-request/index.js:137:21
server:test:  ❯ ../../node_modules/.pnpm/light-my-request@5.8.0/node_modules/light-my-request/index.js:83:14
server:test:  ❯ …
```
> refactor: :test_tube: update createRandomDbSetup as data.js

- apps/client/cypress/e2e/specs/dashboard.e2e.js
- apps/client/cypress/e2e/specs/projects.e2e.js
- apps/client/cypress/e2e/specs/redirection.e2e.js
- apps/client/cypress/e2e/support/commands.js
- apps/client/cypress/e2e/support/func.js
- apps/client/src/api/api.js
- apps/client/src/router/index.js
- apps/client/src/stores/project.js
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/server/src/controllers/project.js
- apps/server/src/models/permission.js
- apps/server/src/models/queries/permission-queries.js
- apps/server/src/models/queries/project-queries.js
- apps/server/src/routes/project-user.spec.js
- apps/server/src/routes/project.spec.js
- packages/test-utils/src/imports/data.js
> feat: :sparkles: add archiveProject btn

- apps/client/cypress/e2e/support/commands.js
- apps/client/src/main.css
- apps/client/src/views/projects/DsoProjects.vue
- apps/client/src/views/projects/DsoRepos.vue
- apps/server/src/controllers/repository.js
- apps/server/src/routes/project-repository.spec.js
Remonter les réponses 20* avant les fetch ansible
Car les fetch prennent trop de temps et font planter la requête
> fix: :bug: controller response before ansible fetch

- apps/client/cypress/components/specs/repo-form.ct.js
- apps/client/cypress/e2e/support/commands.js
- apps/client/src/documentation/doc.md
- apps/server/src/generate-files/generate-ci-files.js
> docs: :memo: update user documentation

- apps/client/cypress/e2e/specs/home.e2e.js
- apps/client/src/App.vue
- apps/client/src/components/SideMenu.vue
> feat: :lipstick: whoami in sidemenu rather than snackbar

- apps/client/cypress/components/specs/permission-form.ct.js
- apps/client/cypress/e2e/specs/repos.e2e.js
- apps/client/src/components/CIForm.vue
- apps/client/src/components/SideMenu.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoRepos.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/client/src/views/projects/ManageEnvironments.vue
> fix: :goal_net: optional chaining to avoid errors on selected project

- apps/client/src/main.css
> fix: :lipstick: enforce ui on disabled dsfrtiles

- apps/client/cypress/e2e/specs/create-project.e2e.js
- apps/client/cypress/e2e/specs/dashboard.e2e.js
- apps/client/cypress/e2e/specs/repos.e2e.js
- apps/client/cypress/e2e/support/commands.js
- apps/client/src/App.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoRepos.vue
- packages/test-utils/src/imports/data.js
in dashboard and repositories pages
Closes #140
> feat: :sparkles: display project and repositories statuses

- apps/client/src/components/PermissionForm.vue
- apps/client/src/stores/project-environment.js
- apps/client/src/stores/project-permission.js
- apps/client/src/stores/project-repository.js
- apps/client/src/stores/project-user.js
- apps/client/src/stores/project.js
- apps/client/src/views/projects/DsoRepos.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/client/src/views/projects/ManageEnvironments.vue
divide project.js store into user, environment, permission & repository stores
> refactor: :recycle: divide project store

- apps/client/cypress/e2e/support/commands.js
- apps/client/src/components/RepoForm.vue
- apps/client/src/views/projects/DsoProjects.vue
- apps/client/src/views/projects/DsoRepos.vue
> fix: :bug: do nothing when tile is disabled

- apps/client/cypress/e2e/specs/redirection.e2e.js
- apps/client/src/utils/keycloak/keycloak.js
- apps/client/src/utils/keycloak/keycloak.spec.js
> perf: :zap: no need to call /account endpoint

- apps/ansible-api/package.json
- apps/server/package.json
- packages/shared/package.json
- packages/shared/src/schemas/repository.js
- packages/shared/src/utils/schemas.spec.js
- pnpm-lock.yaml
> fix: :bug: token should authorize "-"

- apps/client/src/views/CreateProject.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/server/src/controllers/project.js
- packages/shared/src/schemas/project.js
- packages/shared/src/utils/functions.js
- packages/shared/src/utils/schemas.js
- packages/shared/src/utils/schemas.spec.js
> refactor: :recycle: projectname-length-calculation

- helm/templates/_helpers.tpl
- helm/templates/cm-server.yaml
- helm/values.yaml
dispatch in _helpers.tpl
Please update your values.yaml, move containers.client.container.env.___URL to .services
> chore: :wrench: move services url to root Values

- apps/server/src/models/queries/user-queries.js
- apps/server/src/models/user.js
- apps/server/src/utils/env.js
> refactor: :coffin: isAdmin key is no longer used

- apps/client/src/components/DsoSnackbar.vue
- apps/client/src/views/ServicesHealth.vue
> fix: :bug: display hyphen only if service message exists

- apps/client/cypress/e2e/specs/services.e2e.js
- apps/server/env/.env.int-example
- apps/server/src/controllers/environment.js
- apps/server/src/controllers/project.js
- apps/server/src/controllers/repository.js
- apps/server/src/models/log.js
- apps/server/src/models/queries/log-queries.js
- apps/server/src/plugins/core/argo/init.js
- apps/server/src/plugins/core/gitlab/group.js
- apps/server/src/plugins/core/gitlab/index.js
- apps/server/src/plugins/core/gitlab/project.js
- apps/server/src/plugins/core/kubernetes/init.js
- apps/server/src/server.js
- apps/server/src/utils/env.js
- apps/server/src/utils/services.js
- docker/docker-compose.int.yml
- env/.env.int-example
- helm/templates/deployment-server.yaml
- helm/values.yaml
now plz set a configmap (by dso-socle) to configure services URL and access logins
Services URL, services logins are no longer set by helm values
> fix: :bug: patch plugins

- apps/client/src/views/CreateProject.vue
- packages/shared/src/schemas/project.js
- packages/shared/src/utils/schemas.spec.js
> refactor: :necktie: min 2 characters for a project name

- apps/client/cypress/components/specs/repo-form.ct.js
- apps/client/cypress/e2e/support/commands.js
- apps/client/package.json
- apps/client/src/components/CIForm.vue
- pnpm-lock.yaml
> feat: :sparkles: add download link for includes.zip

- apps/client/cypress/e2e/specs/create-project.e2e.js
- apps/client/cypress/e2e/specs/dashboard.e2e.js
- apps/client/src/api/api.js
- apps/client/src/icons.js
- apps/client/src/stores/project.js
- apps/client/src/stores/project.spec.js
- apps/client/src/views/CreateProject.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/server/src/controllers/project.js
- apps/server/src/controllers/repository.js
- apps/server/src/models/project.js
- apps/server/src/models/queries/project-queries.js
- apps/server/src/models/queries/repository-queries.js
- apps/server/src/routes/project.js
- apps/server/src/routes/project.spec.js
- apps/server/src/utils/queries-tools.js
- business-rules.md
- packages/shared/src/schemas/project.js
- packages/shared/src/utils/schemas.spec.js
- packages/test-utils/src/imports/data.js
> feat: :sparkles: add description field for a project

- apps/client/src/components/RangeInput.vue
Cf https://github.com/dnum-mi/dso-console/pull/373#discussion_r1190047273
> refactor: :recycle: use class selector instead of html tag

- apps/client/cypress/e2e/specs/admin/organizations.e2e.js
- apps/client/cypress/e2e/specs/admin/users.e2e.js
- apps/client/cypress/e2e/specs/sidebar.e2e.js
- apps/client/cypress/e2e/support/func.js
- apps/client/src/api/api.js
- apps/client/src/api/api.spec.js
- apps/client/src/components/DsoSnackbar.vue
- apps/client/src/components/SideMenu.vue
- apps/client/src/router/index.js
- apps/client/src/stores/admin/organization.js
- apps/client/src/stores/admin/organization.spec.js
- apps/client/src/stores/organization.js
- apps/client/src/views/admin/ListOrganizations.vue
- apps/server/src/controllers/admin/organizations.js
- apps/server/src/controllers/organization.js
- apps/server/src/models/queries/organization-queries.js
- apps/server/src/routes/admin/index.js
- apps/server/src/routes/admin/organization.js
- apps/server/src/routes/admin/organization.spec.js
- apps/server/src/routes/admin/user.js
- apps/server/src/routes/admin/user.spec.js
- apps/server/src/routes/index.js
- apps/server/src/routes/organization.js
- apps/server/src/routes/organization.spec.js
- packages/shared/src/schemas/index.js
- packages/shared/src/schemas/organization.js
- packages/shared/src/utils/schemas.spec.js
- packages/test-utils/src/imports/data.js
- packages/test-utils/src/random-utils.js
> feat: :sparkles: add organization page for admins

- apps/client/cypress/components/specs/range.input.ct.js
- apps/client/cypress/components/specs/repo-form.ct.js
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/components/PermissionForm.vue
- apps/client/src/stores/user.js
- apps/client/src/stores/user.spec.js
- apps/client/src/views/projects/ManageEnvironments.vue
- apps/server/src/controllers/admin/organizations.js
- apps/server/src/controllers/admin/project.js
- apps/server/src/controllers/admin/user.js
- apps/server/src/routes/admin/organization.spec.js
- apps/server/src/routes/admin/user.spec.js
- apps/server/src/routes/organization.spec.js
- keycloak/realms/realm-dev.json
- packages/shared/src/schemas/environment.js
- packages/shared/src/schemas/project.js
- packages/shared/src/schemas/repository.js
- packages/shared/src/utils/const.js
- packages/shared/src/utils/functions.js
- packages/test-utils/src/random-project.js
- packages/test-utils/src/random-utils.js
Fix https://mattermost-sdit.osc-secnum-fr1.scalingo.io/devsecops/pl/fanys67c6prb3b3cn695nd73zo
> fix: :ambulance: keycloak now sends group path

- apps/server/src/controllers/project.js
> feat: :alien: owner name is required to create Canel user

- apps/server/env/.env-example
- apps/server/env/.env.ci-example
- apps/server/env/.env.int-example
- apps/server/src/controllers/environment.js
- apps/server/src/controllers/permission.js
- apps/server/src/controllers/project.js
- apps/server/src/controllers/repository.js
- apps/server/src/models/queries/users-projects-queries.js
- apps/server/src/plugins/core/gitlab/index.js
- apps/server/src/plugins/core/keycloak/index.js
- apps/server/src/plugins/core/kubernetes/index.js
- apps/server/src/plugins/core/kubernetes/utils.js
- apps/server/src/plugins/core/nexus/project.js
- apps/server/src/plugins/core/sonarqube/user.js
- apps/server/src/routes/project-environment.spec.js
- apps/server/src/routes/project-permission.spec.js
- apps/server/src/routes/project.spec.js
[build: 👷 change client base image to bitnami/nginx](email: owner.email,)
> feat: 👽 owner name is required to create Canel user

- apps/server/src/models/organization.js
- packages/shared/src/schemas/organization.js
- packages/shared/src/utils/schemas.spec.js
Closes #411 
finalement j'ai viré `contributorId` qui ne sert à rien (doublon avec `name`)
> feat: :alien: add keys to source organizations

- apps/server/src/controllers/admin/organizations.js
- apps/server/src/controllers/admin/project.js
- apps/server/src/controllers/admin/user.js
- apps/server/src/routes/admin/index.js
- apps/server/src/routes/admin/organization.spec.js
- apps/server/src/routes/admin/project.spec.js
- apps/server/src/routes/admin/user.spec.js
- apps/server/src/utils/controller.js
> refactor: :recycle: preValidation hook for admin router

- packages/shared/src/utils/const.js
> fix: :lipstick: more contrasted icon color for archived project

- apps/client/cypress/e2e/specs/projects.e2e.js
- apps/client/cypress/e2e/specs/redirection.e2e.js
- apps/client/src/stores/project.js
- apps/client/src/views/projects/DsoProjects.vue
- apps/client/src/views/projects/DsoSelectedProject.vue
Liste des projets, infos projet sélectionné
> :children_crossing: Ajout de l'organisation pour différencier le projet

- apps/client/src/components/DsoSnackbar.vue
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/components/LoadingCt.vue
- apps/client/src/components/MultiSelector.vue
- apps/client/src/components/RepoForm.vue
- apps/client/src/views/CreateProject.vue
- apps/client/src/views/admin/ListClusters.vue
- apps/client/src/views/admin/ListOrganizations.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoRepos.vue
- apps/client/src/views/projects/ManageEnvironments.vue
- apps/server/src/controllers/admin/cluster.ts
- apps/server/src/controllers/environment.ts
- apps/server/src/controllers/project.ts
- apps/server/src/controllers/repository.ts
- misc/controllers.md
- packages/shared/src/utils/const.ts
> feat: :alien: synch controllers with plugin calls

- apps/server/src/plugins/core/argo/app-project.ts
- apps/server/src/plugins/core/argo/index.ts
```js
{
response:
{ statusCode: 404, body: '404 page not found\n', headers: { 'audit-id': '32a1c2d8-7ab5-4e16-a5cd-5fd47b594039', 'cache-control': 'no-cache, private', 'content-type': 'text/plain; charset=utf-8', 'x-content-type-options': 'nosniff', 'x-kubernetes-pf-flowschema-uid': '7db01f3d-d448-4a52-b292-ece35323f703', 'x-kubernetes-pf-prioritylevel-uid': 'd783dd14-fa48-43db-b5fd-e3770bda8433', date: 'Fri, 18 Aug 2023 15:30:42 GMT', 'content-length': '19', connection: 'close' }, request: { uri: { protocol: 'https:', slashes: true, auth: null, host: '10.96.0.1:443', port: '443', hostname: '10.96.0.1', hash: null, search: null, query: null, pathname: '/apis/argoproj.io/v1alpha1/namespaces/dso-argo/appprojects', path: '/apis/argoproj.io/v1alpha1/namespaces/dso-argo/appprojects', href: …
```
> fix: :goal_net: allow deleting environment if not found

- apps/client/cypress/e2e/specs/environments.e2e.js
- apps/client/src/views/admin/ListProjects.vue
https://sonar.apps.c7.numerique-interieur.com/project/issues?resolved=false&types=CODE_SMELL&inNewCodePeriod=false&id=console
> refactor: :recycle: sonar 24082023 analysis

- apps/server/src/generate-files/generate-ci-files.ts
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/organization/admin/business.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/repository/business.ts
- apps/server/src/resources/service/business.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/routes/admin/log.spec.ts
- apps/server/src/routes/admin/organization.spec.ts
- apps/server/src/routes/admin/project.spec.ts
- apps/server/src/routes/admin/user.spec.ts
- apps/server/src/routes/project-environment.spec.ts
- apps/server/src/routes/project.spec.ts
- apps/server/src/utils/controller.ts
- apps/server/src/utils/errors.ts
- apps/server/src/utils/response.ts
`throw error` dans `business` si une `error` est `catch`.
> fix: :goal_net: throw error if catched in business

- apps/client/cypress/components/support/commands.ts
- apps/client/cypress/components/support/index.ts
- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/cypress/e2e/support/func.ts
- apps/client/cypress/e2e/support/index.ts
- apps/client/cypress/tsconfig.json
- apps/client/cypress/types.ts
> test: :label: add types for cypress

- apps/client/src/router/index.ts
- apps/client/src/views/CreateProject.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/server/src/plugins/core/gitlab/index.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/user/business.ts
project could be stuck on initializing because of uncatched errors
> fix: :goal_net: add try catch in checkApi func

- .github/workflows/tests-unit.yml
- .gitlab-ci-dso.yml
- apps/server/src/plugins/core/gitlab/files/.gitlab-ci.yml
Ajout d'une description et d'une valeur par défaut de la branche à synchroniser dans le pipeline de mirror
> feat: :children_crossing: add default branch to sync in mirror pipeline

- apps/client/cypress/e2e/support/commands.ts
- apps/client/src/components/DsoBadge.vue
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/components/LoadingCt.vue
- apps/client/src/components/RepoForm.vue
- apps/client/src/views/CreateProject.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoTeam.vue
- package.json
---------
- au `delete` d'un projet le loader reste indéfiniment. Cest dû au fait que `projecŧ` n'existe plus et fait buguer `DsoBadge`, ce qui fait planter le front
- ajout de conditional chaining sur `DsoBadge` pour ne plus envoyer d'erreur + `v-if` du loader pris en charge par le composant parent
> fix: :bug: add conditional chaining to avoid error in DsoBadge

- apps/server/src/plugins/core/gitlab/index.ts
- apps/server/src/plugins/core/harbor/index.ts
- apps/server/src/plugins/core/harbor/init.ts
- apps/server/src/plugins/core/kubernetes/init.ts
- apps/server/src/plugins/core/kubernetes/misc.ts
- apps/server/src/plugins/index.ts
- apps/server/src/server.ts
---------
seulement les secrets de Gitlab sont remontés aux users
Remontée d'infos de Harbor et Kubernetes
Refacto de l'import des plugins + parrallélisme
> feat: :sparkles: services secrets improvement

- packages/shared/src/utils/functions.spec.ts
- packages/shared/src/utils/functions.ts
> test: :white_check_mark: add tests on shared funtions

- apps/server/src/prisma/migrations/20231026150220_dso/migration.sql
> refactor: :card_file_box: rewrite last migration

- apps/client/.eslintrc.json
- apps/client/jsconfig.json
- apps/client/src/components/PermissionForm.vue
- apps/client/src/views/admin/ListClusters.vue
- apps/client/tsconfig.app.json
- apps/client/tsconfig.json
- apps/client/vite.config.ts
- packages/shared/src/resources/environment/model.ts
- packages/shared/src/resources/permission/model.ts
- packages/shared/src/utils/functions.ts
- packages/shared/tsconfig.json
- packages/test-utils/tsconfig.json
- packages/tsconfig/tsconfig.base.json
Issues numéro:  #536
---------
> refactor: :wrench: update ES module or lib to benefit from latest array functions

- apps/client/src/components/RepoForm.vue
Issues numéro:
- #714 
---------
La description du dépôt d'infrastructure dans le formulaire d'ajout d'un dépôt est ambigüe. 
Amélioration de cette description.
Non
> refactor: :children_crossing: reword infra repository description

- apps/client/cypress/e2e/specs/redirection.e2e.ts
- apps/client/src/router/index.ts
> fix: :bug: fix endless redirect on login if authenticated

- apps/server/src/plugins/core/argo/cluster.ts
> fix: :bug: should not set caData if skipTLSVerify is true

- apps/server/src/plugins/core/gitlab/index.ts
- apps/server/src/plugins/core/gitlab/project.ts
> fix: :lock: root token is not used in new repo credential when synced

- .github/workflows/tests-unit.yml
> ci: :construction_worker: fix branch name on manually triggered sonar scan

- .github/workflows/lint.yml
- .github/workflows/tests-component.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests-unit.yml
---------
Les fichiers de tests (unitaires, composants et bout en bout) sont désormais ignorés dans le calcul de duplication de code de Sonarqube.
> ci: :construction_worker: remove test files duplication count in sonar

- apps/server/src/plugins/hooks/project.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/routes/project.spec.ts
> fix: :alien: add owner in archiveProject hookpayload

- apps/client/cypress/e2e/specs/repos.e2e.ts
- apps/client/src/components/RepoForm.vue
- packages/shared/src/schemas/repository.ts
- packages/shared/src/utils/schemas.spec.ts
> Fix/no uppercase in reponame#833

- .github/workflows/npm.yml
> chore: :green_heart: fix yq expression

- .github/workflows/npm.yml
- .github/workflows/release.yml
> chore: :green_heart: script to edit packages version before publish

- apps/server/src/plugins/core/gitlab/group.ts
---------
La recherche de group Gitlab lors de la suppression d'un groupe ne vérifie que l'organisation parente mais ne fais pas de vérification sur l'égalité stricte du nom du groupe.
La recherche de groupe Gitlab prend désormais en compte la vérification de stricte égalité du nom du groupe.
> fix: :bug: fix gitlab group deletion

- apps/client/cypress/components/specs/team-ct.ct.ts
- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/cypress/e2e/specs/team.e2e.ts
- apps/client/cypress/e2e/support/commands.ts
- apps/client/src/api/api.ts
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/components/TeamCt.vue
- apps/client/src/icons.ts
- apps/client/src/router/index.ts
- apps/client/src/stores/admin/project.spec.ts
- apps/client/src/stores/admin/project.ts
- apps/client/src/stores/project-environment.ts
- apps/client/src/stores/project-user.spec.ts
- apps/client/src/stores/project-user.ts
- apps/client/src/views/ServicesHealth.vue
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/projects/DsoSelectedProject.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/client/src/views/projects/ManageEnvironments.vue
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/environment/controllers.ts
- apps/server/src/resources/project/admin/business.ts
- apps/server/src/resources/project/admin/controllers.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/project/queries.ts
- apps/server/src/resources/user/controllers.ts
- apps/server/src/routes/admin/project.spec.ts
- apps/server/src/routes/admin/project.ts
- apps/server/src/routes/project.spec.ts
- packages/shared/src/resources/environment/openApiSchema.ts
> feat: :sparkles: minimal backoffice for admin

- apps/server/src/plugins/core/kubernetes/quota.ts
> fix: :bug: missed limits

- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/src/api/api.ts
- apps/client/src/stores/admin/project.ts
- apps/client/src/views/admin/ListProjects.vue
- apps/server/src/plugins/core/keycloak/index.ts
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/project/queries.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/utils/controller.ts
- packages/shared/src/resources/organization/dto.ts
- packages/shared/src/resources/organization/openApiSchema.ts
- packages/shared/src/resources/project/dto.ts
- packages/shared/src/resources/project/openApiSchema.ts
- packages/shared/src/utils/functions.ts
---------
Actuellement lesadmins reçoivent la liste compléte des projets
Ajout de champ de filtre et de recherche dans la vue projets des administrateurs
Non
> feat: :children_crossing: add filtering on admin projects view

- .github/ISSUE_TEMPLATE/config.yml
- apps/client/src/components/SideMenu.vue
> docs: :memo: update documentation url

- apps/client/src/components/CIForm.vue
- apps/client/src/components/ClusterForm.vue
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/components/PermissionForm.vue
- apps/client/src/components/TeamCt.vue
- apps/client/src/router/index.ts
- apps/client/src/stores/admin/cluster.ts
- apps/client/src/utils/func.ts
- apps/client/src/views/CreateProject.vue
- apps/client/src/views/admin/ListClusters.vue
- apps/client/src/views/admin/ListLogs.vue
- apps/client/src/views/admin/ListOrganizations.vue
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/admin/ListQuotas.vue
- apps/client/src/views/admin/ListStages.vue
- apps/client/src/views/admin/ListUser.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoProjects.vue
- apps/client/src/views/projects/DsoRepos.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/client/src/views/projects/ManageEnvironments.vue
> refactor: :recycle: handle error types in front

- apps/server/src/plugins/index.ts
- helm/templates/cm-scripts.yaml
and change plugin script
---------
> chore: :loud_sound: add log if cant import plugin

- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/src/api/api.ts
- apps/client/src/components/CIForm.vue
- apps/client/src/components/PermissionForm.vue
- apps/client/src/icons.ts
- apps/client/src/router/index.ts
- apps/client/src/stores/admin/project.ts
- apps/client/src/views/CreateProject.vue
- apps/client/src/views/admin/ListClusters.vue
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/admin/ListQuotas.vue
- apps/client/src/views/admin/ListStages.vue
- apps/client/src/views/admin/ListUser.vue
- apps/client/src/views/projects/DsoProjects.vue
- apps/client/src/views/projects/DsoRepos.vue
- apps/client/src/views/projects/ManageEnvironments.vue
- apps/server/package.json
- apps/server/src/resources/project/admin/business.ts
- apps/server/src/resources/project/admin/controllers.spec.ts
- apps/server/src/resources/project/admin/controllers.ts
- apps/server/src/resources/project/queries.ts
- packages/shared/src/resources/project/openApiSchema.ts
- pnpm-lock.yaml
> feat: :sparkles: download projects data button for admins

- apps/server/src/plugins/hooks/environment.ts
- apps/server/src/plugins/hooks/index.ts
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/environment/controllers.spec.ts
- apps/server/src/resources/environment/controllers.ts
- apps/server/src/resources/environment/queries.ts
- apps/server/src/resources/project/business.ts
Issues numéro:  #890 
---------
- hooks concernés : `initializeEnvironment`, `deleteEnvironment`
- nouvelle clé dans la payload : `environments : { environment: string (non de l'env), stage: string (nom du type d'env)}[]`
> feat: :sparkles: add project environments to hook payload

- .github/workflows/npm.yml
---------
Les paquets npm ne sont pas publiés lors des releases.
Les paquets sont correctement *(j'espère)* publiés lors des releases.
Non
> ci: :green_heart: fix npm publish workflow

- apps/client/cypress.config.ts
- apps/client/cypress/components/specs/cluster-form.ct.ts
- apps/client/cypress/components/specs/environment-form.ct.ts
- apps/client/cypress/tsconfig.json
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/components/RepoForm.ct.ts
> chore: 🔧 configure ts to preserve symlinks

- apps/server/package.json
- pnpm-lock.yaml
> fix: :pushpin: pin axios version to avoid vite error

- apps/client/src/App.vue
- apps/client/src/components/CIForm.vue
- apps/client/src/components/ClusterForm.vue
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/components/PermissionForm.vue
- apps/client/src/router/index.ts
- apps/client/src/utils/func.ts
- apps/client/src/views/CreateProject.vue
- apps/client/src/views/admin/ListClusters.vue
- apps/client/src/views/admin/ListLogs.vue
- apps/client/src/views/admin/ListOrganizations.vue
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/admin/ListQuotas.vue
- apps/client/src/views/admin/ListStages.vue
- apps/client/src/views/admin/ListUser.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoProjects.vue
- apps/client/src/views/projects/DsoRepos.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/client/src/views/projects/ManageEnvironments.vue
> refactor: :recycle: handle front error in vue handler

- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/environment/controllers.spec.ts
- apps/server/src/resources/repository/business.ts
- apps/server/src/resources/repository/controllers.spec.ts
---------
Validation des schémas de dépôt et environnement avant création
> fix: :goal_net: validate schema before creating repo or env

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/npm.yml
- .github/workflows/tests-component.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests-unit.yml
- apps/client/Dockerfile
- apps/client/src/components/RepoForm.ct.ts
- apps/server/Dockerfile
- ci/act/workflows/ci.yml
- package.json
> chore: :arrow_up: upgrade node to LTS

- packages/test-utils/src/utils/random-utils.ts
---------
En cas de dépôt privé (aléatoire dans les TU), la donnée générée par `faker.internet.username` ne respectait pas le schéma joi.
> test: :clown_face: bad faker type choice made repository unit test occasionally failed

- apps/client/cypress/e2e/support/commands.ts
- apps/client/src/components/ClusterForm.vue
- apps/client/src/components/QuotaForm.vue
- apps/client/src/components/RepoForm.vue
- apps/client/src/components/StageForm.vue
- apps/client/src/views/admin/ListClusters.vue
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/admin/ListQuotas.vue
- apps/client/src/views/admin/ListStages.vue
- apps/client/src/views/projects/DsoRepos.vue
- apps/client/src/views/projects/ManageEnvironments.vue
---------
Sur une liste de tuiles, quand on en sélectionne une, la page est immense parce que le formulaire s'incruste dans la vue.
On ne voit que la liste des tuiles ou que le formulaire (avec un petit bouton pour revenir aux tuiles), plus les deux en même temps.
> feat: :children_crossing: better ux for forms in tiles

- helm/templates/deployment-server.yaml
> build: :zap: change initcontainers image

- apps/client/src/App.vue
- apps/server/src/resources/user/business.ts
---------
En cas d'erreur lors de l'ajout ou du retrait d'un membre au projet, le projet est passé en échec et reste verrouillé.
Désormais le projet n'est pas passé en échec en cas de d'erreur dans la gestion des membres (mais l'erreur est quand même remontée au front dans la snackbar).
> feat: :necktie: do not fail and lock project for membership reasons

- .gitignore
- ci/kind/configs/cluster/Chart.yaml
- ci/kind/configs/cluster/templates/kind-config.yml
- ci/kind/configs/cluster/values.yaml
- ci/kind/run-create.sh
- env/dso-values-dev.yaml
- env/kind-values.example.yml
> chore: :technologist: improve dx by passing external plugin dir

- apps/client/vite.config.ts
---------
https://github.com/cypress-io/cypress/issues/25913#issuecomment-1847454142
> fix: :test_tube: trying to fix ct test

- apps/client/vite.config.ts
> fix: :test_tube: trying to optimize dependancies for failing modules

- apps/server/src/plugins.ts
- pnpm-lock.yaml
> refactor: :recycle: enforce typescript:S6544 rule

- .vscode/settings.json
- package.json
- pnpm-lock.yaml
> chore: :wrench: fix vscode config

- package.json
- patches/fastify-keycloak-adapter@2.1.10.patch
- pnpm-lock.yaml
---------
Le typage du user sur la librairie `fastify-keycloak-adapter` nous fait perdre des types.
Le typage du user sur la librairie `fastify-keycloak-adapter` est retiré pour récupérer des types.
Non
> fix: :label: add missing fastify keycloak adapter patch to improve types

- plugins/argo/src/app-project.ts
- plugins/argo/tsconfig.json
- plugins/harbor/src/permission.ts
- plugins/harbor/src/robot.ts
- plugins/harbor/src/utils.ts
- plugins/harbor/tsconfig.json
- plugins/keycloak/src/group.ts
- plugins/keycloak/tsconfig.json
- plugins/sonarqube/src/group.ts
- plugins/sonarqube/src/project.ts
- plugins/sonarqube/src/user.ts
- plugins/sonarqube/tsconfig.json
- plugins/vault/src/class.ts
- plugins/vault/src/functions.ts
- plugins/vault/tsconfig.json
---------
Ajout de types sur les plugins
Non
> refactor: :label: add plugins types to enforce strict mode

- .github/workflows/cd.yml
---------
Le build en multi arch est désactivé.
Le build en multi arch est activé.
Non
> chore: :construction_worker: enable multi arch build on new release

- apps/server/src/resources/cluster/admin/queries.ts
- apps/server/src/resources/organization/admin/controllers.ts
- apps/server/src/resources/repository/business.ts
- apps/server/src/resources/repository/controllers.spec.ts
- apps/server/src/resources/repository/queries.ts
- apps/server/src/resources/service/business.ts
- apps/server/src/resources/service/controllers.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/resources/user/controllers.spec.ts
- apps/server/src/resources/user/controllers.ts
- apps/server/src/resources/user/role-queries.ts
- apps/server/src/utils/business.ts
- apps/server/src/utils/controller.ts
- apps/server/src/utils/logger.ts
- apps/server/src/utils/response.ts
- packages/hooks/src/hooks/repository.ts
- packages/shared/src/openApiSchemas/repository.ts
- packages/shared/src/schemas/cluster.ts
- packages/shared/src/schemas/repository.ts
- packages/shared/src/utils/schemas.spec.ts
- plugins/gitlab/src/project.ts
> refactor: :rotating_light: fix typescript errors in server

- packages/hooks/README.md
> refactor: :speech_balloon: update hooks readme

- .github/workflows/scan.yml
- ci/act/workflows/scan.yml
---------
Il y a des conflits lors de l'export des artefacts (liés à la montée de version majeur de l'action en question)
Il n'y a plus de conflits
Non
> ci: :green_heart: fix artifacts conflicts upload

- .vscode/extensions.json
> Remove deprecated NPM extension from VSCode suggestions.

- .github/workflows/ci.yml
- docker/docker-compose.integ.yml
- plugins/keycloak/src/group.ts
---------
En mode integration le volume des plugins core est bind avec le dossier des plugins externes.
En mode integration le volume des plugins core est correctement bind avec le dossier des plugins core.
Non
> fix: :technologist: fix docker volumes for integ mode

- apps/server/src/plugins/core/gitlab/group.ts
- apps/server/src/plugins/core/nexus/project.ts
> fix: :bug: missing check in search group

- .github/workflows/scan.yml
---------
Il y a conflit sur le nom de l'artefact de résumé du scan des images back et front.
Il n'y a plus de conflit sur le nom des artefacts.
Non
> ci: :construction_worker: fix vuln report artifact conflict

- packages/hooks/src/index.ts
- packages/hooks/src/utils/logger.ts
- plugins/argocd/src/cluster.ts
- plugins/argocd/src/functions.ts
- plugins/argocd/src/utils.ts
- plugins/gitlab/src/functions.ts
- plugins/harbor/src/functions.ts
- plugins/keycloak/src/functions.ts
- plugins/kubernetes/src/namespace.ts
- plugins/kubernetes/src/secret.ts
- plugins/nexus/src/project.ts
- plugins/sonarqube/src/check.ts
- plugins/sonarqube/src/group.ts
- plugins/sonarqube/src/project.ts
- plugins/sonarqube/src/user.ts
- plugins/vault/src/functions.ts
> fix: :bug: add a common error parser for logs

- .github/workflows/release.yml
---------
La CI ne modifie plus les versions des `package.json` de `server` et `client`.
Le versionning est de nouveau opérationnel.
Non
> ci: :green_heart: fix release packages version auto bump

- apps/server/src/prepare-app.spec.ts
- apps/server/src/prepare-app.ts
- apps/server/src/server.spec.ts
- apps/server/src/server.ts
- apps/server/vitest.config.ts
> test: :white_check_mark: split server.ts and test

- plugins/keycloak/package.json
- plugins/keycloak/src/class.ts
> refactor: :recycle: small fix before release on api

- plugins/gitlab/src/class.ts
- plugins/gitlab/src/repositories.ts
- plugins/gitlab/src/utils.ts
Issues numéro: #980 
---------
> Create infra-apps repo

- apps/client/src/stores/admin/project.spec.ts
- apps/client/src/stores/admin/project.ts
- apps/client/src/stores/project.spec.ts
- apps/client/src/stores/project.ts
- apps/client/src/views/admin/ListProjects.vue
> fix: :bug: reload user projects after hooks replay

- plugins/gitlab/package.json
- plugins/gitlab/src/repositories.ts
> fix: :ambulance: gitlab plugin deleted public repo secret

- apps/server/package.json
- apps/server/vite.config.ts
- apps/server/vitest.config.ts
- pnpm-lock.yaml
> test: :wrench: update to vitest 1.4

- plugins/sonarqube/package.json
- plugins/sonarqube/src/functions.ts
- plugins/sonarqube/src/index.ts
- plugins/sonarqube/src/project.ts
> feat: :sparkles: add sonar properties var file to gitlab

- .gitlab-ci-dso.yml
> build: :green_heart: add sonar test

- apps/server/src/utils/hook-wrapper.ts
- apps/server/src/utils/mocks.ts
- apps/server/src/utils/proxy.spec.ts
- apps/server/src/utils/proxy.ts
> fix: :zap: manage hook concurrency execution

- apps/client/package.json
- pnpm-lock.yaml
---------
Fix un bug où les tests Cypress ne se lancent pas bien sur Firefox : https://github.com/cypress-io/cypress/issues/29172
> ci: :green_heart: upgrade cypress to fix firefox broken tests

- plugins/kubernetes/package.json
- plugins/kubernetes/src/class.ts
> fix: :ambulance: change kubernetes logic

- apps/client/vite.config.ts
---------
Le footer du client porte la valeur par défaut de l'application `vpr-dev`.
Le footer du client contient le bon numéro de version.
Non.
> fix: :bug: app version in client footer

- apps/client/cypress/e2e/specs/services-health.e2e.ts
- apps/client/src/api/xhr-client.ts
- apps/client/src/components/SideMenu.vue
- apps/client/src/router/index.ts
- apps/server/src/resources/service/business.ts
- apps/server/src/resources/service/controllers.spec.ts
- apps/server/src/resources/service/router.ts
- apps/server/src/utils/keycloak.ts
- packages/test-utils/src/utils/random-utils.ts
> feat: :safety_vest: allow unlogged users to access services health

- apps/server/src/init/db/index.ts
- packages/test-utils/src/imports/data.ts
> refactor: :label: changes data.ts structure and imports

- apps/client/cypress/e2e/specs/admin/zones.e2e.ts
- apps/server/src/resources/zone/admin/business.ts
- apps/server/src/resources/zone/admin/controllers.spec.ts
- apps/server/src/resources/zone/admin/queries.ts
> feat: :safety_vest: check existing zone slug before creating one

- plugins/gitlab/package.json
- plugins/gitlab/src/class.ts
- plugins/gitlab/src/repositories.ts
- plugins/vault/package.json
- plugins/vault/src/class.ts
> fix: :ambulance: gitlab secret

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/npm.yml
- .github/workflows/tests-component.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests-unit.yml
- apps/client/Dockerfile
- apps/client/cypress/components/specs/repo-form.ct.ts
- apps/server/Dockerfile
- package.json
---------
Nodejs passe en `v20.12.2`.
Non
> chore: upgrade nodejs to v20.12.2

- README.md
---------
Ajout d'un section concernant les releases dans le fichier `README.md`.
Non
> docs: :memo: add release section in readme

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
---------
Les templates d'issues comportent désormais une section `Définition du fini`.
Non.
> chore: :memo: add definition of done in issue templates

- plugins/argocd/src/functions.ts
- plugins/kubernetes/src/api.ts
- plugins/kubernetes/src/class.ts
> propal évolution

- apps/server/src/prisma/migrations/20240329172938_dso/migration.sql
> fix: :ambulance: correct sql query for zoneId

- apps/client/Dockerfile
- apps/server/Dockerfile
- package.json
- pnpm-lock.yaml
> build: :arrow_up: update pnpm to 9.0.6

- packages/shared/package.json
> chore: :bookmark: missed release due to conflict

- apps/client/cypress/components/specs/services-config.ct.ts
- apps/client/src/components/ServicesConfig.vue
- apps/client/src/stores/project-services.spec.ts
- apps/client/src/stores/project-services.ts
- apps/client/src/stores/services-monitor.ts
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/projects/DsoServices.vue
> fix: :bug: stores should have unique names

- apps/client/cypress/e2e/specs/admin/users.e2e.ts
- apps/client/src/App.vue
- apps/client/src/api/users.ts
- apps/client/src/components/TeamCt.vue
- apps/client/src/stores/admin/user.ts
- apps/client/src/stores/user.spec.ts
- apps/client/src/stores/user.ts
- apps/client/src/views/DsoHome.vue
- apps/client/src/views/admin/ListOrganizations.vue
- apps/client/src/views/admin/ListUser.vue
- apps/client/src/views/projects/DsoServices.vue
- apps/server/src/resources/user/admin/business.ts
- apps/server/src/resources/user/admin/controllers.spec.ts
- apps/server/src/resources/user/admin/router.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/utils/hook-wrapper.ts
- apps/server/src/utils/mocks.ts
- packages/hooks/src/hooks/hook-misc.ts
- packages/hooks/src/hooks/hook-user.ts
- packages/hooks/src/hooks/index.ts
- packages/shared/src/contracts/user.ts
- packages/shared/src/schemas/user.ts
- plugins/keycloak/src/functions.ts
- plugins/keycloak/src/group.ts
- plugins/keycloak/src/index.ts
ETAdmins je peux désigner des admins depuis la console
---------
> feat: :sparkles: handle keycloak admin group membership from console

- plugins/gitlab/src/user.ts
> fix: :ambulance: unhandled promise gitlab

- apps/client/cypress/e2e/specs/repos.e2e.ts
- apps/client/src/views/projects/DsoRepos.vue
> fix: :bug: missing await and ambiguous message

- apps/server/src/utils/hook-wrapper.ts
- packages/hooks/package.json
- packages/hooks/src/hooks/hook.ts
- packages/shared/package.json
- packages/shared/src/schemas/config.ts
- plugins/harbor/package.json
- plugins/harbor/src/functions.ts
- plugins/harbor/src/index.ts
- plugins/harbor/src/infos.ts
- plugins/harbor/src/robot.ts
- plugins/harbor/src/utils.ts
Ajout d'un robot disponible aux utilisateurs pour lire sur la registry
> feat: :sparkles: create a user usable robot for harbor

- package.json
> chore: :bug: add missing env for docker integ build

- apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
- apps/server/src/resources/cluster/admin/business.ts
- apps/server/src/resources/cluster/admin/controllers.spec.ts
- apps/server/src/resources/cluster/queries.ts
> fix: :bug: update cluster logic

- apps/client/cypress/components/specs/environment-form.ct.ts
- apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
- apps/client/cypress/e2e/specs/admin/stages.e2e.ts
- apps/client/cypress/e2e/specs/admin/zones.e2e.ts
- apps/client/cypress/e2e/specs/environments.e2e.ts
- apps/client/src/api/clusters.ts
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/stores/admin/cluster.spec.ts
- apps/client/src/stores/admin/cluster.ts
- apps/client/src/stores/cluster.ts
- apps/client/src/views/projects/ManageEnvironments.vue
- apps/server/src/resources/cluster/admin/business.ts
- apps/server/src/resources/cluster/admin/router.ts
- apps/server/src/resources/cluster/business.ts
- apps/server/src/resources/cluster/queries.ts
- apps/server/src/resources/cluster/router.ts
- packages/shared/src/contracts/cluster.ts
- packages/shared/src/schemas/cluster.ts
> refactor: :recycle: split clusters routes, contracts and stores

- packages/hooks/src/utils/logger.ts
> fix: :bug: add try catch to parsing plugin error

- plugins/kubernetes/src/class.ts
> fix: :bug: manage if no users in project

- apps/server/src/resources/project/business.ts
> fix: :bug: why is it useful ?

- plugins/harbor/package.json
- plugins/harbor/src/functions.ts
- plugins/harbor/src/infos.ts
- plugins/harbor/src/project.ts
- pnpm-lock.yaml
> feat: :sparkles: allow harbor quota limit

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/npm.yml
- .github/workflows/tests-component.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests-unit.yml
- .gitignore
- apps/client/Dockerfile
- apps/server/Dockerfile
- ci/act/workflows/ci.yml
- package.json
- pnpm-lock.yaml
> chore: :arrow_up: upgrade pnpm

- plugins/argocd/src/functions.ts
- plugins/argocd/src/index.ts
- plugins/argocd/src/infos.ts
> feat: :sparkles: argocd extra repositories

- apps/client/cypress/components/specs/choice-selector.ct.ts
- apps/client/src/components/ChoiceSelector.vue
- pnpm-lock.yaml
> refactor: :art: introduce new component for multi-select

- apps/client/cypress/e2e/specs/admin/users.e2e.ts
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/admin/ListUser.vue
> feat: :sparkles: add text filter for admin user list

- apps/server/src/resources/environment/business.ts
- apps/server/src/utils/env.ts
- packages/shared/src/schemas/cluster.ts
- packages/shared/src/schemas/project.ts
> refactor: :fire: remove ts errors

- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/environment/router.ts
- apps/server/src/resources/log/admin/router.ts
- apps/server/src/resources/project/queries.ts
- apps/server/src/resources/quota/admin/business.ts
- apps/server/src/resources/quota/admin/controllers.spec.ts
- apps/server/src/resources/quota/queries.ts
- apps/server/src/resources/stage/admin/business.ts
- apps/server/src/resources/stage/admin/controllers.spec.ts
- apps/server/src/resources/stage/business.ts
- apps/server/src/resources/stage/queries.ts
- packages/shared/src/contracts/environment.ts
- packages/shared/src/contracts/log.ts
- packages/shared/src/schemas/environment.ts
- packages/shared/src/schemas/quota.ts
- packages/shared/src/schemas/stage.ts
- packages/shared/src/utils/const.ts
> refactor: :label: improve project and environment contracts

- apps/server/src/connect.ts
- apps/server/src/generate-files/router.ts
- apps/server/src/init/db/index.ts
- apps/server/src/resources/environment/queries.ts
- apps/server/src/resources/system/db/controllers.ts
- apps/server/src/resources/zone/admin/business.ts
- apps/server/src/resources/zone/admin/queries.ts
- apps/server/src/utils/controller.ts
- apps/server/src/utils/env.ts
- apps/server/src/utils/fastify.ts
- apps/server/src/utils/proxy.ts
- apps/server/src/utils/queries-tools.ts
- apps/server/tsconfig.json
> refactor: :label: fix lasts ts errors

- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/projects/DsoDashboard.vue
> fix: :bug: interface suppression & add explication

- docker/docker-compose.dev.yml
- docker/docker-compose.prod.yml
> chore: :technologist: comment keycloak dsfr in compose

- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/src/views/admin/ListProjects.vue
> feat: :sparkles: truncate description

- plugins/argocd/src/functions.ts
> feat: 🎨 change subpath of deployments

- apps/client/cypress/e2e/specs/dashboard.e2e.ts
- apps/client/cypress/e2e/specs/environments.e2e.ts
- apps/client/cypress/e2e/specs/repos.e2e.ts
- apps/client/src/components/EnvironmentForm.vue
- apps/client/src/components/RepoForm.vue
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/environment/controllers.spec.ts
- apps/server/src/resources/repository/business.ts
- apps/server/src/resources/repository/controllers.spec.ts
> feat: :sparkles: prevent env and repo deletion if project is locked

- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/cypress/e2e/specs/environments.e2e.ts
- apps/client/src/api/environments.ts
- apps/client/src/stores/project-environment.ts
- apps/client/src/stores/project-repository.ts
- apps/client/src/views/admin/ListClusters.vue
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/projects/ManageEnvironments.vue
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/environment/queries.ts
- apps/server/src/resources/environment/router.ts
- apps/server/src/resources/project/admin/business.ts
- apps/server/src/resources/project/queries.ts
- apps/server/src/resources/repository/business.ts
- apps/server/src/resources/repository/router.ts
- packages/shared/src/contracts/environment.ts
- packages/shared/src/schemas/environment.ts
Replace https://github.com/cloud-pi-native/console/pull/1183
---------
> refactor: :recycle: smaller api call for projects

- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/cypress/e2e/specs/repos.e2e.ts
- apps/client/src/stores/project-repository.ts
- apps/server/src/resources/repository/controllers.spec.ts
- apps/server/src/resources/repository/router.ts
- packages/shared/src/contracts/repository.ts
- packages/shared/src/schemas/repository.ts
> fix: :bug: support slashes in syncRepository branchName

- apps/server/src/resources/cluster/admin/controllers.spec.ts
- apps/server/src/resources/environment/controllers.spec.ts
- packages/shared/src/schemas/cluster.ts
- packages/shared/src/schemas/project.ts
- packages/shared/src/utils/schemas.spec.ts
This reverts commit 1d72394e3fd4bac774962ef8812a96a60efe7cae.
---------
> Revert "chore: :memo: add documentaion on schemas"

- apps/client/src/components/ChoiceSelector.vue
- apps/client/src/components/ClusterForm.vue
- apps/client/src/components/QuotaForm.vue
- apps/client/src/components/StageForm.vue
- apps/client/src/components/ZoneForm.vue
> refactor: :zap: choice selector return array of valueKeys

- apps/server/src/resources/cluster/admin/business.ts
- apps/server/src/resources/cluster/admin/controllers.spec.ts
- apps/server/src/resources/cluster/queries.ts
> refactor: :zap: improve cluster environments query

- apps/server/src/resources/index.ts
> fix: :lock: serialize sevice monitor response

- apps/client/src/stores/user.spec.ts
- apps/client/src/stores/user.ts
- apps/server/src/resources/cluster/admin/business.ts
- apps/server/src/resources/cluster/business.ts
- apps/server/src/resources/organization/business.ts
- apps/server/src/resources/organization/controllers.spec.ts
- apps/server/src/resources/organization/router.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/project/controllers.spec.ts
- apps/server/src/resources/project/queries.ts
- apps/server/src/resources/project/router.ts
- apps/server/src/resources/quota/business.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/resources/user/queries.ts
- apps/server/src/resources/user/router.ts
- packages/eslintconfig/index.js
- packages/shared/src/contracts/user.ts
- packages/shared/src/schemas/user.ts
> refactor: :necktie: auto signup from front

- README.md
- apps/server/src/server.ts
- ci/scripts/run-tests.sh
- packages/test-utils/src/utils/random-utils.ts
> chore: :recycle: minor changes

- apps/client/cypress/components/specs/repo-form.ct.ts
- apps/client/cypress/e2e/specs/repos.e2e.ts
- apps/client/src/components/RepoForm.vue
- apps/server/src/resources/repository/router.ts
> fix: :lipstick: repo should be able to change infra, not infra

- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/cypress/e2e/specs/admin/quotas.e2e.ts
- apps/client/cypress/e2e/specs/environments.e2e.ts
- apps/client/cypress/e2e/support/commands.ts
- apps/client/src/stores/project-environment.ts
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/projects/ManageEnvironments.vue
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/environment/controllers.spec.ts
- apps/server/src/resources/environment/router.ts
- packages/shared/src/contracts/environment.ts
- packages/shared/src/schemas/environment.ts
> refactor: :fire: no need for projectId in environments routes

- packages/hooks/src/utils/logger.ts
- plugins/gitlab/src/functions.ts
- plugins/gitlab/src/utils.ts
Il faudrait faire le tour des logs qui sont déjà sortis pour les inspecter, pour l'instant ça ira
> refactor: :lock: remove sensitive keys in logs

- apps/client/cypress/e2e/specs/admin/logs.e2e.ts
- apps/client/src/stores/admin/log.spec.ts
- apps/client/src/stores/admin/log.ts
- apps/server/src/resources/index-admin.ts
- apps/server/src/resources/index.ts
- apps/server/src/resources/log/admin/business.ts
- apps/server/src/resources/log/business.ts
- apps/server/src/resources/log/controllers.spec.ts
- apps/server/src/resources/log/queries.ts
- apps/server/src/resources/log/router.ts
- apps/server/src/resources/queries-index.ts
- packages/shared/src/api-client.ts
- packages/shared/src/contracts/log.ts
> refactor: 🚚 move log route

- apps/server/src/resources/index.ts
> fix: :ambulance: not ready for project reponse validation

- apps/client/src/components/EnvironmentForm.vue
- plugins/gitlab/package.json
- pnpm-lock.yaml
> fix: :bug: env name error not displayed

- apps/server/src/resources/cluster/admin/business.ts
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/organization/business.ts
- apps/server/src/resources/permission/business.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/repository/business.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/utils/hook-wrapper.ts
> fix: :art: harmonize hook calling in business

- apps/client/src/components/ClusterForm.vue
- packages/shared/src/schemas/cluster.ts
Issues numéro: https://github.com/cloud-pi-native/console/issues/1261
---------
> fix: :bug: require tls serverName

- plugins/argocd/src/functions.ts
---------
Les paramètres passés à argocd pointe sur le répertoire helm/ (en dur) dans chaque repo d'infra.
On cherche la présence d'un fichier `values.yaml` pour déterminer l'éventuel répertoire Helm à déployer dans le repo d'infra + la présence d'un fichier spécifique à l'environnement cible dans ce même répertoire.
> feat: :rocket: add helm detection and list values files

- plugins/argocd/src/functions.ts
> fix: :bug: search Helm values on HEAD ref instead of main

- packages/shared/src/schemas/cluster.ts
- plugins/gitlab/src/class.ts
- plugins/gitlab/src/repositories.ts
> fix: :ambulance: clone private repositories in gitlab plugin

- packages/hooks/src/utils/logger.ts
---------
Des secrets pouvaient apparaitre dans les messages d'erreurs (ex : token Vault)
Tous les headers sont masqués pour éviter l'affichage des tokens ou credentials http
> fix: :lock: do not display credentials in error messages

- plugins/gitlab/src/class.ts
---------
Possible erreur quand un dépôt d'infra est vide (zéro commit)
Gestion de ce cas d'erreur pour éviter le plantage
> fix: :ambulance: fix error on getArgoRepo when the infra repository is empty (zero commit)

- plugins/gitlab/src/class.ts
- pnpm-lock.yaml
> fix: :ambulance: handle missing commit in gitlab repo

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/npm.yml
- .github/workflows/release.yml
- .github/workflows/tests-component.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests-unit.yml
- ci/act/workflows/lint.yml
- ci/act/workflows/tests-component.yml
- ci/act/workflows/tests-deploy.yml
- ci/act/workflows/tests-e2e.yml
- ci/act/workflows/tests-unit.yml
Mise à jour des Github Actions.
Non.
> ci: :construction_worker: upgrade github actions

- apps/client/src/router/index.ts
> refactor: :recycle: group admin routes

- plugins/argocd/package.json
- plugins/argocd/src/env.d.ts
- plugins/argocd/src/functions.ts
- plugins/vault/src/class.ts
- plugins/vault/src/functions.ts
- plugins/vault/src/index.ts
- pnpm-lock.yaml
---------
Pas de permissions spécifique au projet dans Vault
Un AppRole est créé pour autoriser le projet à gérer ses secrets.
> feat: :sparkles: add project dedicated approle and policy in vault

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/npm.yml
Les paquets ne sont pas publiés sur npm lors des releases.
Les paquets sont systématiquement publiés sur npm lors des releases et la CI vérifie si la version a été mise à jour en cas de changements dans le dossier `dist`.
Non.
> ci: :construction_worker: check for package version update and publish

- .github/workflows/npm.yml
> ci: :construction_worker: fix npm package version check

- apps/client/cypress/e2e/specs/repos.e2e.ts
- apps/client/src/stores/project-repository.ts
- apps/client/src/views/projects/DsoRepos.vue
- apps/server/src/resources/repository/business.ts
- apps/server/src/resources/repository/controllers.spec.ts
- apps/server/src/resources/repository/router.ts
- apps/server/src/utils/hook-wrapper.ts
- packages/hooks/package.json
- packages/hooks/src/hooks/hook-misc.ts
- packages/shared/package.json
- packages/shared/src/schemas/repository.ts
- plugins/gitlab/files/.gitlab-ci.yml
- plugins/gitlab/package.json
- plugins/gitlab/src/class.ts
- plugins/gitlab/src/functions.ts
https://github.com/cloud-pi-native/gitlab-ci-catalog/pull/16/files
---------
> feat: :sparkles: option to mirror all branches

- apps/client/src/App.vue
- apps/client/src/router/index.ts
- apps/client/src/stores/user.spec.ts
- apps/client/src/stores/user.ts
- apps/client/src/views/admin/DsoAdmin.vue
> refactor: :recycle: parent admin check

- apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/cypress/e2e/specs/admin/roles.e2e.ts
- apps/client/src/components/AdminRoleForm.vue
- apps/client/src/components/ChoiceSelector.vue
- apps/client/src/components/ConfigParam.vue
- apps/client/src/components/ProjectRoleForm.vue
- apps/client/src/components/SuggestionInput.vue
- apps/client/src/components/TeamCt.vue
- apps/client/src/views/admin/AdminRoles.vue
- apps/client/src/views/admin/ListPlugins.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoRoles.vue
> test: :test_tube: add roles test

- apps/client/src/components/TeamCt.vue
> fix: :bug: transfertSelectOptions and more

- apps/client/src/api/xhr-client.ts
- apps/client/src/main.ts
- apps/client/src/utils/keycloak/keycloak.ts
- keycloak/realms/realm-dev.json
> perf: :zap: avoid unuseful keycloak call and auto-refresh

- packages/eslintconfig/package.json
- packages/hooks/package.json
- packages/shared/package.json
- plugins/argocd/package.json
- plugins/keycloak/package.json
- plugins/kubernetes/package.json
- plugins/nexus/package.json
- plugins/sonarqube/package.json
> chore: :hammer: bump packages versions

- apps/client/cypress/components/specs/repo-form.ct.ts
- apps/client/cypress/e2e/specs/repos.e2e.ts
- apps/client/cypress/e2e/support/commands.ts
- apps/client/package.json
- apps/client/src/components/RepoForm.vue
- packages/shared/src/schemas/repository.ts
- packages/shared/src/utils/const.ts
- packages/shared/src/utils/schemas.spec.ts
- pnpm-lock.yaml
> refactor: :children_crossing: encourage cloned repository

- apps/client/src/components/RepoForm.vue
> fix: :lipstick: better repo ui

- .github/workflows/ci.yml
- .github/workflows/scan.yml
- ci/trivy/template-html.tpl
- ci/trivy/template-md.tpl
Un rapport sommaire est écrit dans une issue avant chaque merge sur `main`.
Utilisation de Github Code Scanning pour obtenir des rapport plus détaillés à chaque PR.
Non.
> ci: :construction_worker: improve trivy scan system

- plugins/gitlab/package.json
- plugins/gitlab/src/class.ts
- plugins/gitlab/src/repositories.ts
if a plugin create a repo and then the plugin is not loaded it should not delete the repo
Issues numéro:
---------
> refactor: :recycle: should prevent auto cleanup

- .github/workflows/preview.yml
En cas de multiple déclenchement du workflow, le commentaire de preview n'est pas édité mais un nouveau commentaire est généré.
Le commentaire de preview est bien édité.
Non.
> ci: :construction_worker: add comment tag on preview comment

- apps/client/src/components/AdminRoleForm.vue
- apps/client/src/stores/users.ts
- apps/client/src/views/admin/AdminRoles.vue
- apps/server/src/resources/user/business.spec.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/resources/user/router.ts
- packages/shared/src/contracts/user.ts
- packages/shared/src/schemas/role.ts
- packages/shared/src/schemas/user.ts
- packages/shared/src/schemas/utils.ts
> feat: :sparkles: add users search filter (admin)

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/npm.yml
- .github/workflows/tests-component.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests-unit.yml
- .prototools
- apps/client/Dockerfile
- apps/server/Dockerfile
- package.json
> chore: :arrow_up: upgrade node and pnpm

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/npm.yml
La publication des paquets npm lors de release échoue.
La publication devrait fonctionner car le token est bien passé au workflow enfant.
Non.
> ci: :construction_worker: fix npm packages publish on release

- apps/client/src/stores/project-member.ts
- apps/client/src/views/admin/ListUser.vue
- apps/server/src/resources/user/business.spec.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/resources/user/router.ts
> fix: :bug: fix behaviour of complex querying on user list

- .github/workflows/cd.yml
> build: :construction_worker: auto trigger chart update

- apps/client/src/components/AdminRoleForm.vue
- apps/client/src/components/ProjectRoleForm.vue
- apps/server/src/resources/index.ts
> fix: :ambulance: cbx not checked cause vuedsfr breaking change

- apps/server/src/init/db/utils.ts
- apps/server/src/prisma/migrations/20240919122331_optional_user_id/migration.sql
- apps/server/src/prisma/schema.prisma
- apps/server/src/resources/admin-token/router.ts
- apps/server/src/resources/cluster/business.ts
- apps/server/src/resources/cluster/router.ts
- apps/server/src/resources/environment/business.ts
- apps/server/src/resources/environment/router.ts
- apps/server/src/resources/log/queries.ts
- apps/server/src/resources/organization/business.ts
- apps/server/src/resources/project-member/business.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/project/router.ts
- apps/server/src/resources/repository/business.ts
- apps/server/src/resources/user/business.ts
- apps/server/src/utils/controller.ts
- packages/shared/package.json
- packages/shared/src/contracts/cluster.ts
- packages/shared/src/contracts/log.ts
- packages/shared/src/schemas/cluster.ts
> fix: :passport_control: allow more actions to admin token

- .github/workflows/ci.yml
- plugins/sonarqube/package.json
- plugins/sonarqube/src/functions.ts
- plugins/sonarqube/src/index.ts
> fix: :loud_sound: change log logic in sonarqube plugin

- apps/client/cypress/e2e/specs/admin/projects.e2e.ts
- apps/client/cypress/e2e/specs/dashboard.e2e.ts
- apps/client/src/App.vue
- apps/client/src/components/AdminTokenForm.vue
- apps/client/src/components/ServicesConfig.vue
- apps/client/src/components/TeamCt.vue
- apps/client/src/main.css
- apps/client/src/stores/project.spec.ts
- apps/client/src/stores/project.ts
- apps/client/src/stores/services-monitor.ts
- apps/client/src/views/CreateProject.vue
- apps/client/src/views/admin/ListPlugins.vue
- apps/client/src/views/admin/ListProjects.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/server/src/prisma/migrations/20240928002900_dso/migration.sql
- apps/server/src/prisma/schema.prisma
- apps/server/src/resources/project/queries.ts
- apps/server/src/utils/hook-wrapper.ts
- packages/shared/src/utils/const.ts
- packages/shared/src/utils/functions.ts
- packages/test-utils/src/imports/data.ts
- plugins/gitlab/package.json
- plugins/gitlab/src/functions.ts
- plugins/gitlab/src/index.ts
- plugins/gitlab/src/members.ts
- plugins/kubernetes/package.json
- plugins/kubernetes/src/class.ts
- plugins/kubernetes/src/namespace.ts
> feat: :sparkles: introduce warn status on project

- packages/shared/src/contracts/environment.ts
- packages/shared/src/contracts/repository.ts
> fix: :ambulance: no check on api response

- .github/workflows/scan.yml
La CI est parfois bloquée par le rate limit de téléchargement de l'image Trivy.
La CI continue son exécution et notifie le warning.
Non.
> ci: :construction_worker: bypass trivy rate limit errors

- .github/workflows/build.yml
Les nouveaux builds dans les PR ne déclenchent pas le re-deploiement des preview apps.
Les preview apps sont correctement re-déployées (enfin normalement).
Non.
> ci: :technologist: re-deploy preview apps on new build

- .github/workflows/build.yml
> chore: :green_heart: preview jobs needs to be executed after merge

- .github/workflows/build.yml
- .github/workflows/ci.yml
> ci: :green_heart: fix app preview re-deploy

- .github/workflows/build.yml
- .github/workflows/ci.yml
> ci: :green_heart: really fix re-deploy preview app

- apps/server/src/resources/project-service/business.ts
- packages/hooks/src/services.ts
- plugins/argocd/package.json
- plugins/argocd/src/functions.ts
- plugins/argocd/src/infos.ts
Issues numéro:
---------
Pas de lien vers le argocd d'une zone
Lien vers le argocd de chaque zone du projet
> feat: :lipstick: add argocd urls for each zone

- plugins/argocd/src/functions.ts
> feat: :lipstick: adding the project id in namespace labels

- apps/server/src/plugins.ts
Utilisation de l'ancienne syntax `assert { type: "json" }` pour importer les plugins.
Utilisation de l'ancienne syntax `with { type: "json" }` pour importer les plugins.
Non.
> fix: :bug: update depracated import assertion type syntax

- apps/client/src/components/RepoForm.vue
- apps/client/src/views/projects/DsoProjectWrapper.vue
- apps/server/src/resources/project/business.spec.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/project/queries.ts
- apps/server/src/resources/system/router.ts
- apps/server/src/utils/env.ts
- apps/server/src/utils/fastify.ts
- apps/server/src/utils/hook-wrapper.ts
- packages/shared/package.json
- packages/shared/src/utils/functions.spec.ts
- packages/shared/src/utils/functions.ts
- plugins/argocd/package.json
- plugins/argocd/src/app-project.ts
- plugins/argocd/src/applications.ts
- plugins/argocd/src/functions.ts
- plugins/argocd/src/index.ts
- plugins/argocd/src/utils.ts
- plugins/gitlab/package.json
- plugins/gitlab/src/class.ts
- plugins/harbor/package.json
- plugins/harbor/src/robot.ts
- plugins/kubernetes/package.json
- plugins/kubernetes/src/class.ts
- plugins/kubernetes/src/misc.ts
- plugins/nexus/package.json
- plugins/nexus/src/project.ts
- plugins/vault/package.json
- plugins/vault/src/class.ts
> fix: :bug: minors plugins fix and front

- plugins/nexus/package.json
- plugins/nexus/src/infos.ts
- plugins/nexus/src/maven.ts
- plugins/nexus/src/npm.ts
- plugins/nexus/src/project.ts
- plugins/nexus/src/utils.ts
> feat: :sparkles: nexus customizable write policy

- apps/client/src/views/admin/AdminProject.vue
> refactor: :children_crossing: see env localization in admin project

- plugins/nexus/src/infos.ts
- plugins/nexus/src/project.ts
> refactor: :sparkles: option to disable Nexus

- apps/client/cypress/e2e/specs/02-profile.e2e.ts
- apps/client/cypress/e2e/specs/admin/organizations.e2e.ts
- apps/client/cypress/e2e/specs/not-found.e2e.ts
- apps/client/src/components/OperationPanel.vue
- apps/client/src/components/ProjectLogsViewer.vue
- apps/client/src/components/ReplayButton.vue
- apps/client/src/router/index.ts
- apps/client/src/stores/project.ts
- apps/client/src/utils/project-utils.ts
- apps/client/src/views/admin/AdminProject.vue
- apps/client/src/views/projects/DsoDashboard.vue
- apps/client/src/views/projects/DsoProjectWrapper.vue
- apps/client/src/views/projects/DsoRepos.vue
- apps/client/src/views/projects/DsoTeam.vue
- apps/client/src/views/projects/ManageEnvironments.vue
- apps/server/src/resources/project-member/business.ts
> fix: :bug: fix weird front behviours

- .github/workflows/cd.yml
- plugins/vault/src/functions.ts
> fix: :bug: fix vault detect api hashicorp

- .github/workflows/build.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- La publication de la PR d'update du chart ne se fait que quand le build amd64 et arm64 est effectué.
- La publication de la PR d'update du chart n'attend que le build de la version amd64 de l'image.
Non.
> ci: :construction_worker: improve build pipeline

- apps/client/src/components/DsoSnackbar.vue
- packages/hooks/src/hooks/hook.spec.ts
- packages/hooks/src/utils/utils.ts
- plugins/vault/README.md
- plugins/vault/src/config.ts
- plugins/vault/src/functions.ts
> refactor: :recycle: support disabling vault-secrets

- plugins/argocd/package.json
- plugins/argocd/src/functions.ts
- plugins/argocd/src/index.ts
- plugins/gitlab/package.json
- plugins/gitlab/src/class.ts
- plugins/gitlab/src/env.d.ts
- plugins/gitlab/src/functions.ts
- plugins/gitlab/src/index.ts
- plugins/gitlab/src/repositories.ts
Issues numéro:
---------
Gestion du repo d'infra dans le upsertProject
Gestion du repo d'infra dans le upsertZone
> feat: :art: use upsert zone hook to manage infra repo

- apps/client/package.json
- apps/client/src/App.vue
- apps/client/src/components/ReloadPrompt.vue
- apps/client/src/env.d.ts
- apps/client/src/main.ts
- apps/client/tsconfig.json
- apps/client/vite.config.ts
- pnpm-lock.yaml
- https://vite-pwa-org.netlify.app/frameworks/vue.html#vue-3
> feat: :sparkles: enable pwa on frontend

- apps/client/cypress/e2e/specs/admin/tokens.e2e.ts
- apps/server/src/resources/user/business.ts
> fix: :ambulance: broken admin token

- plugins/argocd/src/functions.ts
- plugins/keycloak/package.json
- plugins/keycloak/src/env.d.ts
- plugins/keycloak/src/functions.ts
- plugins/vault/src/class.ts
- plugins/vault/src/functions.ts
- plugins/vault/src/index.ts
- pnpm-lock.yaml
Issues numéro:
---------
Création d'un KV dans Vault pour les secrets de la zone
> feat: :construction: zone kv store management

- apps/client/src/App.vue
- apps/client/src/components/ChoiceSelector.vue
- apps/client/src/components/DsoSnackbar.vue
- apps/client/src/components/ServicesConfig.vue
- apps/client/src/utils/project-utils.ts
- apps/client/src/views/admin/ListUser.vue
- apps/client/vite.config.ts
> refactor: :lipstick: improve layout

- .github/workflows/build.yml
- .github/workflows/ci.yml
- Le check des versions de paquets npm ne se fait que lorsque la branche de base est `main`.
- Le code HTTP de l'appel de redéploiement de la preview est capturé pour sortir en erreur en cas d'échec (le workflow continue tout de même).
Non.
> ci: :construction_worker: improve ci workflow

- apps/server/src/resources/project/business.spec.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/utils/hook-wrapper.ts
- plugins/kubernetes/src/namespace.ts
- plugins/sonarqube/src/functions.ts
> fix: :bug: retry delete project is failed

- apps/client/cypress/e2e/specs/redirection.e2e.ts
- apps/client/src/router/index.ts
> fix: :bug: fix not displaying swagger

- apps/client/src/App.vue
- apps/client/src/views/admin/ListUser.vue
This reverts commit 229d355dd39fc7ac92610dce52dd728098e32a10.
Issues numéro:
---------
> Revert "refactor: :lipstick: improve layout"

- apps/server/src/resources/cluster/queries.ts
- apps/server/src/utils/hook-wrapper.ts
- packages/hooks/src/hooks/index.ts
- plugins/argocd/src/cluster.ts
- plugins/argocd/src/functions.ts
- plugins/argocd/src/index.ts
- plugins/argocd/src/zone.ts
- plugins/gitlab/src/index.ts
- plugins/vault/src/class.ts
- plugins/vault/src/functions.ts
- plugins/vault/src/index.ts
> feat: :sparkles: store cluster secret in Vault

- apps/server/src/prisma/migrations/20241112102015_add_provisionning_version/migration.sql
- apps/server/src/prisma/schema/project.prisma
- apps/server/src/resources/log/queries.ts
- apps/server/src/utils/hook-wrapper.spec.ts
- apps/server/src/utils/hook-wrapper.ts
- packages/hooks/src/hooks/hook-project.ts
- plugins/kubernetes/package.json
- plugins/kubernetes/src/class.ts
- plugins/kubernetes/src/namespace.ts
> feat: track project version provisioning

- plugins/gitlab/src/class.ts
- plugins/gitlab/src/repositories.ts
> fix: :ambulance: fix gitlab ci config file

- plugins/gitlab/package.json
- plugins/gitlab/src/class.ts
- plugins/gitlab/src/repositories.ts
> fix: fix gitlab, no first commit on cloned repository

- apps/client/cypress/e2e/specs/create-project.e2e.ts
- apps/server/src/resources/project/business.ts
- apps/server/src/resources/project/queries.ts
> fix: :bug: duplicates name should not be already allowed

- apps/client/package.json
- apps/client/src/components/AdminRoleForm.vue
- apps/client/src/views/profile/PersonalAccessTokens.vue
- pnpm-lock.yaml
> refactor: :recycle: avoid unuseful computed

- apps/client/src/stores/project.ts
> fix: :bug: names displayed twice at project creation

- plugins/kubernetes/package.json
- plugins/kubernetes/src/class.ts
- plugins/vault/README.md
- plugins/vault/package.json
- plugins/vault/src/config.ts
- plugins/vault/src/functions.ts
- plugins/vault/src/vso.ts
> feat: :sparkles: vault plugin, switch to deploy or not vaultconnections

- apps/server/src/resources/project-service/business.ts
- apps/server/src/resources/project/queries.ts
- packages/hooks/package.json
- packages/hooks/src/services.ts
- packages/shared/package.json
- plugins/argocd/package.json
- plugins/argocd/src/infos.ts
- plugins/gitlab/package.json
- plugins/gitlab/src/infos.ts
- plugins/keycloak/package.json
- plugins/kubernetes/package.json
- plugins/vault/package.json
- plugins/vault/src/infos.ts
> chore: :package: update package.json

- apps/server/src/resources/quota/queries.ts
> fix: :ambulance: owner of a project cannot see attached private quota

- apps/client/src/api/xhr-client.ts
> fix: :bug: auto re login when session expiry

- migrations/v9/Migrate v9-FR.md
- migrations/v9/Migrate v9.md
- migrations/v9/migrate.js
> refactor: migrate script should not delete old group

- plugins/gitlab/src/index.ts
- plugins/gitlab/src/utils.ts
> feat: :sparkles: auto create projectRootDir in Gitlab

- plugins/gitlab/src/class.ts
> refactor: :zap: improve gitlab project search

- apps/server/src/resources/project-service/business.ts
- apps/server/src/resources/project/queries.ts
- packages/hooks/package.json
- packages/hooks/src/services.ts
> refactor: :recycle: add projectId to url params

- apps/client/src/components/Badge.vue
- apps/client/src/components/LogsViewer.vue
- apps/client/src/components/PaginationCt.vue
- apps/client/src/components/ProjectBanner.vue
- apps/client/src/components/ProjectLogsViewer.vue
- apps/client/src/router/index.spec.ts
- apps/client/src/router/index.ts
- apps/client/src/stores/project.ts
- packages/shared/src/schemas/log.ts
- packages/shared/src/utils/schemas.spec.ts
> refactor: :children_crossing: display projectid and can use it in url

- apps/server/src/resources/admin-token/business.spec.ts
- apps/server/src/resources/environment/business.spec.ts
- apps/server/src/resources/environment/business.ts
refactor: :fire: delete some dead code
Issues numéro:
---------
> refactor: :test_tube: add some tests

- apps/client/src/views/projects/DsoProjects.vue
> refactor: :children_crossing: change projects tils

- packages/hooks/src/hooks/hook-cluster.ts
- packages/hooks/src/hooks/hook-misc.ts
- packages/hooks/src/hooks/hook-project.ts
- packages/hooks/src/hooks/hook-user.ts
- packages/hooks/src/hooks/hook-zone.ts
- packages/hooks/src/hooks/hook.spec.ts
- packages/hooks/src/hooks/hook.ts
- packages/hooks/src/index.ts
on n'a jamais utilisé cette fonction, 0 implémentation dans le code
et je prévois autre chose pour la validation
> refactor: :fire: remove validation step in hook

- plugins/gitlab/files/mirror.sh
Issues numéro: #1557
---------
mirror.sh argument r non supporté
mirror.sh argument r supporté
non
ajout de l'affichage des arguments fournis dans la sortie du job
> :bug: fix and improve mirror.sh

- apps/client/src/components/EnvironmentForm.vue
Issues numéro:
---------
Impossible de modifier un environnement associé à un quota privé (même en tant qu'administrateur)
Revue des règles de gestion pour une implémentation correcte
> fix: :bug: update condition to allow private quota modification

- plugins/keycloak/src/functions.ts
> fix: :bug: add missing scope when creating keycloak client

- CHANGELOG.md
Issues numéro: https://github.com/cloud-pi-native/socle/issues/514
---------
Duplicate entries in changelog.
Manual fix. Long term fix is to not use merge commits anymore.
No.
No.
> fix: :wrench: duplicate changelog entries

- plugins/argocd/package.json
- plugins/argocd/src/functions.ts
- plugins/gitlab/package.json
- plugins/gitlab/src/class.ts
sources repositories in project should include all project's repos to allow multi sources argocd application and avoid waste applications
Issues numéro:
---------
> fix: allowed sources repositories

- plugins/nexus/src/monitor.ts
> fix: :bug: adapt status analysis to Nexus 3.78 response

- .github/workflows/cd.yml
> ci: :construction_worker: set the scope of the GH token for automatic Helm chart releases

- plugins/argocd/README.md
Closes #1632 
---
Ajout d'un README pour le Plugin ArgoCD, incluant un diagramme technique rédigé en MermaidJS (intégré à Github pour son rendu) afin d'arriver à déterminer ce qui est du process "historique" (amené à disparaître) du process "futur" (GitOps et déclaratif).
> Diagrammes techniques ArgoCD

- packages/shared/src/schemas/repository.ts
- packages/shared/src/utils/const.ts
https://github.com/cloud-pi-native/console/issues/1638
Issues numéro:
---------
Pas de contrôle sur le nom du dépôts mis à part la min le max et les caractères interdits
Contrôle sur le nom précédent et ajout d'une blacklist
No
> fix 🔧 : Gérer les noms de dépôt interdits

- README.md
- apps/client/cypress/e2e/specs/team.e2e.ts
- apps/server/Dockerfile
- plugins/argocd/src/cluster.ts
Closes: #1681 
---------
Bug detailed in #1681.
Fix the bug.
No.
No.
> fix(#1681): :bug: missing kv creation if not exists

- plugins/nexus/src/monitor.ts
Issues numéro:
---------
We are getting degraded state for Nexus upon upgrade to 3.83.1 version.
Remove not supported `Thread Deadlock Detector` check.
No.
No.
> fix: :bug: adapt status analysis to Nexus 3.83.1 response

- README.md
Issues numéro:
---------
When following Readme step for quickstart, we got the following error with `pnpm build`:
```
@cpn-console/server:build: Found 176 errors in 30 files.
@cpn-console/server:build: 
@cpn-console/server:build: Errors  Files
@cpn-console/server:build:      1  src/mocks/prisma.ts:1
@cpn-console/server:build:        1  src/prisma.ts:1
@cpn-console/server:build:        9  src/resources/admin-role/business.ts:1
@cpn-console/server:build:        2  src/resources/admin-role/queries.ts:2
@cpn-console/server:build:        5  src/resources/admin-token/business.ts:3
@cpn-console/server:build:       11  src/resources/cluster/business.ts:1
@cpn-console/server:build:       12  src/resources/cluster/queries.ts:1
@cpn-console/server:build:        5 …
```
> docs: :memo: fix build error

- .github/workflows/playwright.yml
- apps/client/cypress/e2e/specs/01-logs.e2e.ts
- apps/client/cypress/e2e/specs/redirection.e2e.ts
- apps/client/cypress/e2e/support/commands.ts
- apps/client/package.json
- docker/docker-compose.ci.yml
- docker/docker-compose.dev.yml
- docker/docker-compose.local.yml
- docker/docker-compose.prod.yml
- keycloak/realms/realm-dev.json
- playwright/e2e-tests/keycloak.spec.ts
- pnpm-lock.yaml
Issues numéro: https://github.com/cloud-pi-native/socle/issues/795
---------
Playwright test for Keycloak are on version `docker.io/bitnami/keycloak:23.0.7`.
Playwright test for Keycloak are on version `docker.io/bitnamilegacy/keycloak:26.1.3-debian-12-r0`.
Yes, some locator changed between versions.
Prepare the Socle version upgrade: https://github.com/cloud-pi-native/socle/pull/834
> test(playwright): :test_tube: upgrade to docker.io/bitnamilegacy/keycloak:26.1.3-debian-12-r0

- .github/workflows/playwright.yml
- playwright/README.md
- playwright/config/keycloak.ts
- playwright/e2e-tests/keycloak.spec.ts
Issues numéro: https://github.com/cloud-pi-native/socle/issues/789
---------
Playwright tests only runs on local development environment or on CI.
We are creating the possibility to run playwright test on a real exposed environment.
No.
Must merge #1720 first.
> test(playwright): 🧑‍💻 playwright on exposed cluster
